#! /usr/bin/env bash
#
# Create and publish docker image
#
# USAGE: ./build <tag>
#
# Example: ./build 1.0
#

TAG=$1

# build
docker build --tag liufengyun/lctes22:$TAG .

# publish
# docker push liufengyun/lctes22:$TAG

# export
# docker save liufengyun/lctes22:$TAG | gzip > lctes22-$TAG.tar.gz

# load
# docker load < lctes22-$TAG.tar.gz

# pandoc README.md -o README.pdf --pdf-engine=xelatex --from markdown --template eisvogel --listings

# gzip -9 -c README.pdf lctes2022-paper14.pdf lctes22-1.0.tar.gz > lctes22-artifact.tgz